/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.JobInfo;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-12-04T16:51:06.704Z")

@Api(value = "JobInfo", description = "the JobInfo API")
public interface JobInfoApi {

    @ApiOperation(value = "get superstepblock's data", nickname = "jobinfo", notes = "Get the superstepblock's data ", response = JobInfo.class, tags={ "developers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "job information", response = JobInfo.class),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @RequestMapping(value = "/JobInfo",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<JobInfo> jobinfo(@NotNull @ApiParam(value = "job id", required = true) @Valid @RequestParam(value = "jobid", required = true) String jobid);

}
